# Generated by Django 4.0.5 on 2024-03-01 10:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('inventory', '0006_rename_staff_order_created_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='datetime',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='product',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('DryFly GIN', 'DryFly GIN'), ('Rocky Mountain GIN', 'Rocky Mountain GIN'), ('Few American GIN', 'Few American GIN'), ('DryFly Vodka', 'DryFly Vodka'), ('Hooch Vodka Citron', 'Hooch Vodka Citron'), ('Journeyman Whisky', 'Journeyman Whisky'), ('FireWater Whisky', 'FireWater Whisky'), ('Tequila', 'Tequila'), ('Violetta', 'Violetta')], max_length=20, null=True),
        ),
    ]
