# Generated by Django 4.0.5 on 2024-03-01 11:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0007_product_datetime_product_user_alter_product_category'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='user',
            new_name='username',
        ),
    ]
