# Generated by Django 4.0.5 on 2024-03-01 11:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0008_rename_user_product_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='username',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
